import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '/components/Navbar'
import { useState } from 'react'
import Sidebar from '../../components/Navbar/Sidebar'
import { Footer } from '@mantine/core'
import Featured from '../../components/Featured'


export default function Home() {
  return (
    <>
      <Head>
        <title>Best Bet </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/**navbar */}
      <Navbar/>
      <div className='grid grid-cols-4'>
      <Sidebar/> 
      <div className='col-span-2'></div>
      </div>
      {/**navbar */}
      <Featured />
      <div>
      {/**featured */}

      </div>
      <div>
        {/**footer */}
      <Footer />
      </div>
      



    </>
  )
}
